objects/Lead.object
<CustomObject>
    <fields>
        <fullName>OptInEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opt In Email NL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptInMail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opt In Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptInPhone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opt In Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptInSMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opt In SMS</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CIN_Lead_Process</fullName>
        <active>true</active>
        <businessProcess>CIN_Lead_Process</businessProcess>
        <description>Lead Process</description>
        <label>CIN Lead Process</label>
    </recordTypes>
</CustomObject>

classes/CIN_WS002_APIConsent_TEST.cls
@isTest
public class CIN_WS002_APIConsent_TEST {
    
    @TestSetup
    private static void testSetup() {
        
        Id rcLead = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('CIN_Lead_Process').getRecordTypeId();
        
        Lead leadtest = new Lead(LastName = 'Lead TEST', RecordTypeId = rcLead, Status = 'New', OptInMail__c = True, OptInPhone__c = True, OptInEmail__c = True, OptInSMS__c = True);
        insert leadtest;
    }

    @isTest
    static void UpdateConsentInRDVTest(){
        
        Test.setMock(HttpCalloutMock.class, new MCK_WS002_APIConsent());
        Lead leadupdate = [SELECT Id, OptInMail__c, OptInPhone__c, OptInEmail__c, OptInSMS__c FROM Lead WHERE LastName = 'Lead TEST'];
        
        Lead leadOld = leadupdate;
        leadOld.OptInMail__c = False;
        leadOld.OptInPhone__c = False;
        leadOld.OptInEmail__c = False;
        leadOld.OptInSMS__c = False;
                
        Test.startTest();

        Database.update(leadOld);
        
        Test.stopTest();
        
    }
}